[package]
name = "fenrir"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
crossterm = "0.29"
serde = "1.0.138"
serde_derive = "1.0.138"
serde_json = "1.0"
viuer = "0.9"
image = "0.25"
bytesize = "2.0.1"